config/routes.rb
Rails.application.routes.draw do
  resources :presences do 
    collection do
      get :confirmation
      get :export
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/presence.rb
class Presence < ApplicationRecord
  validates :name, :arena, :phone_number, :question1, :question2, :question3, :question4, :start_time, :end_time, :presence => {:message => "est requis." }

  self.per_page = 50
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/presences_controller.rb
require 'csv'

class PresencesController < ApplicationController
  before_action :set_presence, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "ahmldm", password: "fnq6aMuQZLR4Rgm6", except: [:new, :create, :confirmation]

  # GET /presences
  # GET /presences.json
  def index
    @presences = Presence.page(params[:page]).order("activity_date DESC").order("REPLACE(start_time, ':', '')::int DESC")
    days = Presence.all.map {|i| i.created_at.to_date }

    @days = days.uniq.sort
  end

  # GET /presences/1
  # GET /presences/1.json
  def show
  end

  # GET /presences/new
  def new
    @presence = Presence.new

    time_zoned = Time.now.round_off(30.minutes).in_time_zone("America/New_York")
    hour = time_zoned.hour
    minutes = '%02d' % time_zoned.min
    end_hour = hour + 1
    end_hour = 1 if end_hour > 24
  end_hour = 7
  siudhzgfuysgdfbsaidfbihsabdfihbsiuefbbf = 'asbdfuabvdhbasdbajsdbjasb'
    @presence.start_time = "#{hour}:#{minutes}"
    @presence.end_time = "#{end_hour}:#{minutes}"

    @presence_times = presence_times
  end

  # GET /presences/1/edit
  def edit
    @presence_times = presence_times
  end

  # POST /presences
  # POST /presences.json
  def create
    @presence = Presence.new(presence_params)
    @presence.activity_date = Date.today
    respond_to do |format|
      if @presence.save
        format.html { redirect_to confirmation_presences_url, notice: 'Presence was successfully created.' }
        format.json { render :show, status: :created, location: @presence }
      else
        format.html { render :new }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presences/1
  # PATCH/PUT /presences/1.json
  def update
    respond_to do |format|
      if @presence.update(presence_params)
        format.html { redirect_to @presence, notice: 'Presence was successfully updated.' }
        format.json { render :show, status: :ok, location: @presence }
      else
        format.html { render :edit }
        format.json { render json: @presence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presences/1
  # DELETE /presences/1.json
  def destroy
    @presence.destroy
    respond_to do |format|
      format.html { redirect_to presences_url, notice: 'Presence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirmation
  end

  def export
    date = params[:selectdate]
    arena = params[:arena]
    start_date = DateTime.parse(date).beginning_of_day
    end_date = DateTime.parse(date).end_of_day
    presences = Presence.where(:created_at => start_date..end_date, :arena => arena).order("REPLACE(start_time, ':', '')::int ASC")
    csv_data = CSV.generate(headers: true) do |csv|
      csv << ["Date", "Heure de debut", "Heure de fin", "Nom joueur/benevole", "Accompagnateur", "Telephone", "Arena", "Question 1", "Question 2", "Question 3", "Question 4"]

      presences.each do |p|
        csv << [p.activity_date, p.start_time, p.end_time, p.name, p.attendant, p.phone_number, p.arena, p.question1, p.question2, p.question3, p.question4]
      end
    end

    send_data csv_data, filename: "presence-#{arena}-#{date}.csv"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presence
      @presence = Presence.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def presence_params
      params.require(:presence).permit(:name, :attendant, :phone_number, :arena, :question1, :question2, :question3, :question4, :start_time, :end_time)
    end

    def presence_times
      p_times = []
      (1..24).each do |hour|
        p_times << "#{hour}:00"
        p_times << "#{hour}:30"
      end
      p_times
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AhmldmCovid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="text-center" style="background-color: #011B4C;">
    <div class="container">
      <div class="row">
        <div class="col-sm" style="background-color: #F0F0F0; padding-top: 10%; padding-bottom: 10%; margin-top:10%;">
          <img src="/images/logo.png" class="img-fluid w-25"/>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>
  

app/views/presences/_form.html.erb
<div style="padding-left: 10%; padding-right: 10%;">
<%= form_with(model: presence, local: true) do |form| %>
  <% if presence.errors.any? %>
    <div id="error_explanation" class='invalid-feedback d-block'>
      <h2><%= pluralize(presence.errors.count, "erreur") %> empêche la sauvegarde:</h2>

      <ul>
        <% presence.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for='name'>Confirmation de la présence du joueur/bénévole (Nom, Prénom) <font color=red>*</font></label><br/>
    <small class="form-text text-muted">Doit remplir un autre questionnaire si vous êtes bénévole en plus de votre enfants</small>
    <%= form.text_field :name, :class => 'form-control', required: true%>
  </div>

  <div class="form-group">
    <label for='attendant'>Accompagnateur (Nom, Prénom)</label>
    <%= form.text_field :attendant, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <label for='phone_number'>Numéro de téléphone <font color=red>*</font></label>
    <%= form.text_field :phone_number, :class => 'form-control', required: true %>
  </div>

  <div class="form-group">
    <label for='arena'>A qu'elle arena êtes-vous? <font color=red>*</font></label>
    <%= form.select(:arena, ['Olympia', 'ComplexeAP'], {}, { :class => 'form-control' })%>
  </div>

  <div class="form-group">
    <label for='arena'>Heure de début de l'activité <font color=red>*</font></label>
    <%= form.select(:start_time, @presence_times, {}, { :class => 'form-control' })%>
  </div>

   <div class="form-group">
    <label for='arena'>Heure de fin de l'activité <font color=red>*</font></label>
    <%= form.select(:end_time, @presence_times, {}, { :class => 'form-control' })%>
  </div>

  <div class="form-group">
    <label for='question1'>1-PRÉSENTEZ-VOUS UN DES SYMPTÔMES SUIVANTS: <font color=red>*</font></label><br/>
    <small class="form-text text-muted">Fièvre ou frissons, Apparition ou aggravation de toux, Perte de l'odorat ou du goût, Maux de gorge ou voix enrouée, Essoufflement ou difficulté respiratoire, Symptômes gastro-intestinaux (douleur abdominale, diarrhée vomissements.</small>
    <div class="field">
      <%= form.label :question1, "OUI", :value => "OUI"  %>
      <%= form.radio_button :question1, 'OUI' %>
      <%= form.label :question1, "NON", :value => "NON" %>
      <%= form.radio_button :question1, 'NON', :checked => true %>
    </div>
  </div>
<br/>
  <div class="form-group">
    <label for='question2'>2-PRÉSENTEZ -VOUS DEUX (OU PLUS) DES SYMPTÔMES SUIVANTS: <font color=red>*</font></label><br/>
    <small class="form-text text-muted">Écoulements nasaux, Douleurs musculaires ou courbatures, Fatigue intense, Conjonctivite, Maux de tête, Nausée, perte d’appétit.</small>
    <div class="field">
      <%= form.label :question2, "OUI", :value => "OUI"  %>
      <%= form.radio_button :question2, 'OUI' %>
      <%= form.label :question2, "NON", :value => "NON" %>
      <%= form.radio_button :question2, 'NON', :checked => true %>
    </div>
  </div>
<br/>
  <div class="form-group">
    <label for='question3'>3-AVEZ-VOUS VOYAGÉ À L’ÉTRANGER (Y COMPRIS AUX ÉTATS-UNIS) OU EU UN CONTACT AVEC UNE PERSONNE QUI A VOYAGÉ AU COURS DES 14 DERNIERS JOURS? <font color=red>*</font></label>
    <div class="field">
      <%= form.label :question3, "OUI", :value => "OUI"  %>
      <%= form.radio_button :question3, 'OUI' %>
      <%= form.label :question3, "NON", :value => "NON" %>
      <%= form.radio_button :question3, 'NON', :checked => true %>
    </div>
  </div>
<br/>
  <div class="form-group">
    <label for='question4'>4-AU COURS DES 14 DERNIERS JOURS, AVEZ-VOUS FOURNI DES SOINS OU EU UN CONTACT AVEC UN CAS SYMPTOMATIQUE CONFIRMÉ OU SUSPECTÉ (EN ATTENTE D’UN RÉSULTAT) DE LA COVID-19? <font color=red>*</font></label>
    <div class="field">
      <%= form.label :question4, "OUI", :value => "OUI"  %>
      <%= form.radio_button :question4, 'OUI' %>
      <%= form.label :question4, "NON", :value => "NON" %>
      <%= form.radio_button :question4, 'NON', :checked => true %>
    </div>
  </div>
<br/>
  <p>SI VOUS RÉPONDEZ OUI À L’UNE DE CES QUESTIONS, VEUILLEZ PAR MESURE PRÉVENTIVE:</p>
  <ul>
    <li>Ne pas vous présenter à l’aréna</li>
    <li>Demeurer à la maison et communiquer avec la ligne 1-877-644-4545.</li>
  </ul>
  <br/>
  <div class="actions">
    <%= form.submit "Confirmer ma presence", :class => "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/presences/confirmation.html.erb
<h1>AHMLDM - Présence COVID</h1>
<p>Merci, votre présence a bien été confirmé.</p>
<%= link_to 'Confirmer à nouveau', new_presence_path %>

app/views/presences/edit.html.erb
<h1>Editing Presence</h1>

<%= render 'form', presence: @presence %>

<%= link_to 'Show', @presence %> |
<%= link_to 'Back', presences_path %>

app/views/presences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Presences</h1>
<div>
  <p>Exporter le jour <select id="exportDay">
    <% @days.each do |day| %>
      <option><%=day%></option>
    <% end %>
  </select> 
  pour l'arena <select id="exportArena">
    <option>Olympia</option>
    <option>ComplexeAP</option>
  </select> en excel
  <input type="button" id="exportButton" value="Telecharger" /></p>

</div>
<br/>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Heure de début</th>
      <th scope="col">Heure de fin</th>
      <th scope="col">Nom joueur/benevole</th>
      <th scope="col">Accompagnateur</th>
      <th scope="col">Phone number</th>
      <th scope="col">Arena</th>
      <th scope="col">Question 1</th>
      <th scope="col">Question 2</th>
      <th scope="col">Question 3</th>
      <th scope="col">Question 4</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @presences.each do |presence| %>
      <tr>
        <td><%= I18n.l(presence.activity_date,format: :long) %></td>
        <td><%= presence.start_time %></td>
        <td><%= presence.end_time %></td>
        <td><%= presence.name %></td>
        <td><%= presence.attendant %></td>
        <td><%= presence.phone_number %></td>
        <td><%= presence.arena %></td>
        <td><%= presence.question1 %></td>
        <td><%= presence.question2 %></td>
        <td><%= presence.question3 %></td>
        <td><%= presence.question4 %></td>
        <td><%= link_to 'Show', presence %></td>
        <td><%= link_to 'Edit', edit_presence_path(presence) %></td>
        <td><%= link_to 'Destroy', presence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div><%= will_paginate @presences %></div>
<br>

<%= link_to 'New Presence', new_presence_path %>
<script type="text/javascript">
    document.getElementById("exportButton").onclick = function () {
      query = document.getElementById("exportDay").value;
      arena = document.getElementById("exportArena").value;
      location.href = "/presences/export?selectdate=" + query + "&arena=" + arena;
    };
</script>

app/views/presences/new.html.erb
<h1>AHMLDM - Présence COVID</h1>
<p>Présences et formulaire COVID pour les Panthères du Lac des Deux-Montagnes</p>
<%= render 'form', presence: @presence %>
<script type="text/javascript">
  $( document ).ready(function() {
    // returns '#input' for 'https://www.techiedelight.com/#input'
    var hash = $(location).prop('hash').substring(1);;
    if (hash !== "" && $("#presence_arena option[value="+hash+"]").length > 0) {
      $("#presence_arena").val(hash);
    }
  });
</script>

app/views/presences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @presence.name %>
</p>

<p>
  <strong>Attendant:</strong>
  <%= @presence.attendant %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @presence.phone_number %>
</p>

<p>
  <strong>Arena:</strong>
  <%= @presence.arena %>
</p>

<p>
  <strong>Question1:</strong>
  <%= @presence.question1 %>
</p>

<p>
  <strong>Question2:</strong>
  <%= @presence.question2 %>
</p>

<p>
  <strong>Question3:</strong>
  <%= @presence.question3 %>
</p>

<p>
  <strong>Question4:</strong>
  <%= @presence.question4 %>
</p>

<%= link_to 'Edit', edit_presence_path(@presence) %> |
<%= link_to 'Back', presences_path %>

app/views/welcome/index.html.erb
<h2>Nothing to see here, except</h2>
<p>
  The time is now: <%= Time.now %>
</p>